# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ind', models.BooleanField(default=True)),
                ('prefix_txt', models.CharField(blank=True, default='', max_length=25)),
                ('first_nm_txt', models.CharField(default='', max_length=255)),
                ('middle_nm_txt', models.CharField(blank=True, default='', max_length=255)),
                ('last_nm_txt', models.CharField(default='', max_length=255)),
                ('suffix_txt', models.CharField(blank=True, default='', max_length=25)),
                ('nickname_txt', models.CharField(blank=True, default='', max_length=255)),
                ('pronounced_txt', models.CharField(blank=True, default='', max_length=255)),
                ('gender_cd', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='', max_length=1)),
                ('birth_dt', models.DateTimeField(null=True)),
                ('other_id', models.CharField(blank=True, default='', max_length=50)),
                ('address_street1', models.CharField(default='', max_length=50)),
                ('address_street2', models.CharField(blank=True, default='', max_length=50)),
                ('city_cd', models.CharField(default='', max_length=50)),
                ('state_cd', models.CharField(choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NA', 'National'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], default='OR', max_length=2)),
                ('zip_cd', models.CharField(default='', max_length=5)),
                ('zip_cd_ext', models.CharField(blank=True, default='', max_length=4)),
                ('county_nm_txt', models.CharField(blank=True, default='', max_length=50)),
                ('email_txt', models.EmailField(blank=True, default='', max_length=254)),
                ('phone1_number', models.CharField(blank=True, default='', max_length=14)),
                ('phone1_extension', models.CharField(blank=True, default='', max_length=10)),
                ('phone1_type_cd', models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], default='', max_length=15)),
                ('phone2_number', models.CharField(blank=True, default='', max_length=14)),
                ('phone2_extension', models.CharField(blank=True, default='', max_length=10)),
                ('phone2_type_cd', models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], default='', max_length=15)),
                ('phone3_number', models.CharField(blank=True, default='', max_length=14)),
                ('phone3_extension', models.CharField(blank=True, default='', max_length=10)),
                ('phone3_type_cd', models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], default='', max_length=15)),
                ('comments_txt', models.TextField(default='')),
                ('add_dt', models.DateTimeField(auto_now=True)),
                ('edit_dt', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.CharField(blank=True, default='', max_length=50)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, default='', max_length=50)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
