# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecord',
            name='address_street2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='comments_txt',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='county_nm_txt',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='email_txt',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='gender_cd',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='middle_nm_txt',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='nickname_txt',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='other_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone1_extension',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone1_number',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone1_type_cd',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone2_number',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone2_type_cd',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone3_extension',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone3_number',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone3_type_cd',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='prefix_txt',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='pronounced_txt',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='suffix_txt',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='zip_cd_ext',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
