# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrecord',
            old_name='created_date',
            new_name='add_dt',
        ),
        migrations.RenameField(
            model_name='myrecord',
            old_name='author',
            new_name='added_by',
        ),
        migrations.RemoveField(
            model_name='myrecord',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='myrecord',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='myrecord',
            name='published_date',
        ),
        migrations.AddField(
            model_name='myrecord',
            name='active_ind',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='address_street1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='address_street2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='birth_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='city_cd',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='county_nm_txt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='delete_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='deleted_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='email_txt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='first_nm_txt',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='gender_cd',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='last_nm_txt',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='middle_nm_txt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='nickname_txt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='other_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='person_image',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone1_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone1_number',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone1_type_cd',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone2_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone2_number',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone2_type_cd',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone3_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone3_number',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='phone3_type_cd',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='prefix_txt',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='pronounced_txt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='state_cd',
            field=models.CharField(default='OR', max_length=2),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='suffix_txt',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='zip_cd',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='myrecord',
            name='zip_cd_ext',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
