# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161028_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecord',
            name='address_street1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='address_street2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='birth_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='city_cd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='comments_txt',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='county_nm_txt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='edited_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='email_txt',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='first_nm_txt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='last_nm_txt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='middle_nm_txt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='nickname_txt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='other_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone1_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone1_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone1_type_cd',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone2_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone2_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone2_type_cd',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone3_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone3_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='phone3_type_cd',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile'), ('O', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='prefix_txt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='pronounced_txt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='suffix_txt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='zip_cd',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='myrecord',
            name='zip_cd_ext',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
