# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161013_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecord',
            name='person_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
